# Generated by Django 3.1.5 on 2021-01-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBlog', '0003_auto_20210111_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.CharField(max_length=30),
        ),
    ]
