# Generated by Django 3.1.5 on 2021-01-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBlog', '0004_auto_20210111_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
